#!/usr/bin/bash
#
# Credits: @RarelySukuna 
# FROM File-Sharing-Man <https://t.me/ANIME_domain1>
# t.me/SharingUserbot & t.me/Lunatic0de

# Attemp to Terminate and Remove previous session
if [ ! -d .git ]; then
    git clone https://t.me/ANIME_domain1
    mv tmp_git/.git .
    rm -rf tmp_git
fi

# start
python3 main.py
